# Generated by Django 5.1.7 on 2025-07-28 18:13

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_created_at_alter_task_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان'),
        ),
    ]
